[google_sheets]
type = "service_account"
project_id = "analisis-emociones"
private_key_id = 423281592843
private_key = "-----BEGIN PRIVATE KEY-----\\nABC...\\n-----END PRIVATE KEY-----\\n"
client_email = "azulmelcon@gmail.com"
client_id = "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"
